# Generated by Django 4.2.3 on 2023-07-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_vendido'),
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
